### ISSUE TITLE
Tracking model changes after training

### ISSUE THREAD

**Issue by lensonp** [scattering-central/xrsdkit#190]
Some changes are needed in xrsdkit.models.train.
 
- When the models are trained (and saved), we should specify a directory where the serialized model files would be saved. This requires changes in train_from_dataframe(), save_classification_models(), and save_regression_models(). We can remove the "test" argument, and replace it with an "output_dir" argument, for starters.

- When the models are trained (and saved), we should produce a single file that tracks the changes in all of the models, relative to current models (in xrsdkit/models/modeling_data). This file should specify which models are new, which models have been removed, and the numerical change in all cross-validation metrics.

- We may want to add a function for replacing the current models. This function would take a directory path as input. It would remove all of the current models (from xrsdkit/models/modeling_data), and replace them with the models from the specified directory.

**Comment by Katy-katy** [comment]
@lensonp I have a couple question about it.
1. Should we still have a default directory for our models "inside" xrsdkit or the user must specify a directory? Can the specified dir be xrsdkit/models/modeling_data?

2. The file with training result should be also saved in the same directory as models?

**Comment by lensonp** [comment]
@Katy-katy - answers:

1. Yes, we should still have a directory for the xrsdkit models. The directory that the models are saved to should __not__ usually be xrsdkit/models/modeling_data, because I don't think users should have to be aware of the xrsdkit directory structure. Rather, the user should save their models in some familiar place (like their desktop or working directory), and then there should be a new function that would take the models from that directory and load them into xrsdkit/models/modeling_data.

2. Yes, the training result should be saved in the same directory as the models.

**Comment by lensonp** [comment]
Resolved by #191
